### PR TITLE
Convert documents to pdf and jpg, fixes #109

### LINKED ISSUE #109: Errors when converting using Processors::Document
Converting documents to pdf using libreoffice produces this error:

```
No such file or directory @ unlink_internal - /var/folders/yb/pbl7568x7073w02tyghtk3140000gp/T/thumbnail.pdf
```

Libreoffice converts the document to pdf successfully, but using the name of the source file. So, if your source file is `example.odt` the resulting file is named `example.pdf`. The encoding methods are expecting a file named `thumbnail.pdf`. See:

https://github.com/projecthydra/hydra-derivatives/blob/master/lib/hydra/derivatives/processors/document.rb

### PR DESCRIPTION
**Pull request by awead**
This improves the function of Hydra::Derivatives::Processors::Document and refactors its tests.

* correctly converts documents to pdf and other non-image formats
* jpg conversion is delegated to Hydra::Derivatives::Processors::Image so files are correctly resized
* adds additional units tests; refactors existing tests

### CODE REVIEW

File: lib/hydra/derivatives/processors/document.rb [hunk 1]
```diff
@@ -2,27 +2,41 @@ module Hydra::Derivatives::Processors
...
-      end
-      out_file = File.open(new_output, "rb")
-      output_file_service.call(out_file, directives)
-      File.unlink(out_file)
+    # Converts the document to the format specified in the directives hash.
+    # TODO: file_suffix and options are passed from ShellBasedProcessor.process but are not needed.
+    #       A refactor could simplify this.
+    def encode_file(_file_suffix, _options = {})
+      convert_to_format
+      File.unlink(converted_file)
```
Comment (mjgiarlo) [inline lib/hydra/derivatives/processors/document.rb]: Should we pop an `ensure` here to make sure the deletion happens, even if `convert_to_format` bombs out?

File: lib/hydra/derivatives/processors/document.rb [hunk 2]
```diff
@@ -2,27 +2,41 @@ module Hydra::Derivatives::Processors
...
     end
+
+    private
+
+      # For jpeg files, a pdf is created from the original source and then passed to the Image processor class
+      # so we can get a better conversion with resizing options. Otherwise, the ::encode method is used.
+      def convert_to_format
+        if directives.fetch(:format) == "jpg"
```
Comment (mjgiarlo) [inline lib/hydra/derivatives/processors/document.rb]: I might like to see this magic string declared in a constant and `#freeze`d.

File: lib/hydra/derivatives/processors/document.rb [hunk 3]
```diff
@@ -2,27 +2,41 @@ module Hydra::Derivatives::Processors
...
+          Hydra::Derivatives::Processors::Image.new(converted_file, directives).process
+        else
+          output_file_service.call(File.read(converted_file), directives)
+        end
+      end
+
+      def converted_file
+        @converted_file ||= if directives.fetch(:format) == "jpg"
+                              convert_to("pdf")
```
Comment (mjgiarlo) [inline lib/hydra/derivatives/processors/document.rb]: Or maybe we can we use a symbol here?

File: lib/hydra/derivatives/processors/document.rb (hunk 1 above)
Comment (awead) [inline lib/hydra/derivatives/processors/document.rb]: 👍

Comment (awead) [inline lib/hydra/derivatives/processors/document.rb]: wait, but if conversion doesn't happen the file wouldn't exist.
