### PR TITLE
Fix failing test for creation of JPEG2000 derivatives.

### LINKED ISSUE #118: Non-Backwards-Compatible Change between 3.1.3 and 3.1.4
I think there is a non-backwards-compatible change introduced between 3.1.3 and 3.1.4.  Starting with 3.1.4, I see this error when trying to generate a JP2:

```
      Failure/Error:
        Hydra::Derivatives::Jpeg2kImageDerivatives.create(
          filename,
          outputs: [
            label: 'intermediate_file',
            service: {
              datastream: 'intermediate_file',
              recipe: :default
            },
            url: derivative_url('intermediate_file')
          ]
      
      NoMethodError:
        protected method `long_dim' called for Hydra::Derivatives::Processors::Jpeg2kImage:Class
```

### PR DESCRIPTION
**Pull request by dlpierce**
Fixes #118 by un-protecting some class methods that were originally not actually protected, but then made protected by rubocop. Specs for these methods coming shortly...
.jp2 derivatives tests were still broken due to .txt being used as a default mime-type and extension, so that is explicitly set now.

### CODE REVIEW

File: spec/processors/jpeg2k_spec.rb [hunk 1]
```diff
@@ -54,4 +56,25 @@
       expect(r).to eq(described_class.calculate_recipe(args, 'grey', 7200))
     end
   end
+
+  describe "#encode" do
+    it "executes the external utility" do
+      expect(described_class).to receive(:execute) { 0 }
+      described_class.encode('infile', 'recipe', 'outfile')
+      # expect(Hydra::Derivatives::Processors::ShellBasedProcessor).to have_received(:execute)
```
Comment (jeremyf) [inline spec/processors/jpeg2k_spec.rb]: Please remove the commented out code. It looks like this is tested in the above `expect` segment.

File: spec/processors/jpeg2k_spec.rb [hunk 2]
```diff
@@ -54,4 +56,25 @@
...
+    end
+  end
+
+  describe "#tmp_file" do
+    it "returns a temp file with the correct extension" do
+      f = described_class.tmp_file('test')
+      expect(f).to match(/sufia.*test$/)
```
Comment (jeremyf) [inline spec/processors/jpeg2k_spec.rb]: @cjcolvar You had made mention of being concerned about the "sufia" assumption in file names. Could you take a look here?

I'm wondering if it would be okay to ignore the `sufia` part of the regular expression?

File: lib/hydra/derivatives/processors/jpeg2k_image.rb [hunk 3]
```diff
@@ -73,20 +73,18 @@ def layer_rates(layer_count, compression_numerator)
         rates.map(&:to_s).join(',')
       end
 
-      protected
```
Comment (jeremyf) [inline lib/hydra/derivatives/processors/jpeg2k_image.rb]: I'm seeing that the following methods are now becoming public. What was your reason for removing the `protected` declaration?

Comment (val99erie) [inline lib/hydra/derivatives/processors/jpeg2k_image.rb]: The failing spec that he fixed had this error:

```
8) Transcoding with an attached tiff transcodes
     Failure/Error: long_dim = self.class.long_dim(image)
     
     NoMethodError:
       protected method `long_dim' called for Hydra::Derivatives::Processors::Jpeg2kImage:Class
```

"protected" for class methods apparently doesn't behave in the way you might expect.

Comment (jeremyf) [inline lib/hydra/derivatives/processors/jpeg2k_image.rb]: Thank you @val99erie for the clarification; Always hesitant to `public`-ize new methods, but this sounds like a necessary reason to open the public facing methods.

File: spec/processors/jpeg2k_spec.rb (hunk 2 above)
Comment (cjcolvar) [inline spec/processors/jpeg2k_spec.rb]: That conversation was based on #99 .   I agree that it seems possible to remove the sufia from the regex and maybe change this to an ends_with? ".test".

File: lib/hydra/derivatives/processors/jpeg2k_image.rb (hunk 3 above)
Comment (val99erie) [inline lib/hydra/derivatives/processors/jpeg2k_image.rb]: Here's an older explanation of why it won't work to have a protected class method and then try to call it from within an instance method.  The only receive that is allowed is `self`;  `self.class` won't work.
http://stackoverflow.com/questions/11461262/what-is-the-value-of-self-in-a-rails-model-and-why-arent-obvious-instance-metho/11461333#11461333

Comment (jeremyf) [inline lib/hydra/derivatives/processors/jpeg2k_image.rb]: Thanks for the follow-up. I missed the context that these were class methods as well. I'm all for this change.

File: spec/processors/jpeg2k_spec.rb (hunk 1 above)
Comment (dlpierce) [inline spec/processors/jpeg2k_spec.rb]: Thanks, missed it in the rush for lunch.
